volumes:
  postgres-data:

services:
  app:
    container_name: ambiente-dev
    build: .
    environment:
      POSTGRES_HOSTNAME: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: codechella_db
      POSTGRES_USER: codechella
      POSTGRES_PASSWORD: sup3rs3cr3t
    volumes:
      -  .:/home/toolbox/workspace:cached
    tty: true
  db:
    container_name: postgresdb
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: codechella_db
      POSTGRES_USER: codechella
      POSTGRES_PASSWORD: sup3rs3cr3t
    network_mode: service:app
  pgadmin:
    image: dpage/pgadmin4:9.3
    environment:
      - PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS=['localhost']
      - PGADMIN_DEFAULT_EMAIL=admin@localhost
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_DISABLE_POSTFIX=true
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_CONFIG_GLOBALLY_DELIVERABLE=False
    network_mode: service:app
  mail:
    container_name: smtp4dev
    image: rnwood/smtp4dev
    environment:
      - SERVEROPTIONS__URLS=http://*:2525
      - ASPNETCORE_HTTP_PORTS=2525
    network_mode: service:app
